### ISSUE TITLE
No support for StreamDeck XL

### ISSUE THREAD

**Issue by Subsentient** [abcminiuser/python-elgato-streamdeck#14] opened 2019-07-16 18:44 UTC
Currently no support for StreamDeck XL. Tinkered a bit, looks like the XL has some large differences in the protocol. You'd have expected Elgato to have kept it mostly the same, but nope.

**Comment by abcminiuser** [comment] 2019-07-16 23:44
Darn, can you provide some USB captures? Getting the original is one thing, but I can't really afford to buy their entire lineup with a new variant every few months just for some packet captures.

**Comment by Eastborn** [comment] 2019-07-28 18:35
Uhm, ive ordered a StreamDeck XL and Mini and they should arrive in the coming week. Is there anyone who can help me set things up so you guys can get the information you want? im pretty adept in using the API but actually figuring out hardware profiles and protocols isnt really anything ive done.

My main pc is running windows 10 but i have some a laptop laying around which i can reinstall with whatever needed os if that helps

**Comment by abcminiuser** [comment] 2019-08-03 02:21
Ideally, some USB packet traces from Wireshark (https://www.wireshark.org/) would be great. During installation on Windows, there should be an optional USB tracing module you can opt-into to get the USB packet capturing functionality. Linux would probably be easier, except that I suspect the official software doesn't run on it.

If you can, some captures of the StreamDeck XL under the following circumstances:
1) With all the keys set to black images, set the top left, top right, bottom left and bottom right keys to an all-red image.
2) Set the top-left key to an all blue, all green, and all white image.
3) Set the top-left key to an image that is all black except for the top-left pixel, which is white.
3) With the official software, set the brightness to 0% and 100%.

That should give me enough to hopefully figure out the basic protocol, including how the keys are indexed, and what order the key RGB channels are in, the orientation of the image as displayed on the keys. I'm sure that'll raise further questions, but it should be enough to make a start on basic support.

**Comment by abcminiuser** [comment] 2019-08-03 02:50
Actually, I was able to find some existing libraries in other languages that have at least partial XL support:

https://github.com/OpenMacroBoard/StreamDeckSharp/blob/master/src/StreamDeckSharp/Internals/StreamDeckXlHardwareInfo.cs

https://github.com/bitfocus/elgato-stream-deck-clean-xl/blob/master/index.js

From that, I've made a [new branch](https://github.com/abcminiuser/python-elgato-streamdeck/tree/feature/streamdeckxl) that should at least be able to talk to the device and do everything except set the actual key images. Would you mind trying that out, and post back what the `example_basic.py` and `example_deckinfo.py` scripts show? Key press events, brightness setting, serial number and firmware version should all work.

Looking at the other libraries it seems the XL uses JPEG compression on the images, so Pillow will need to be a hard-dependency for the next version of the library, unfortunately.

**Comment by 64BitsPerMinute** [comment] 2019-09-07 03:04
I just picked up an XL with the hopes of creating user interfaces for it in python.

@abcminiuser Yes, when I connect the XL, it looks like the key press events, brightness settings, serial number, and firmware versions are working. Is there anything else that would help with getting Image data to the Keys? I successfully connected the XL via the node.js library you posted, and validated that at least the 'set a key to a color' function works successfully.

**Comment by 64BitsPerMinute** [comment] 2019-09-07 03:23
Actually, the key mapping seems to be 3 keys off - the first key reports as Key 3, and then the 29th Key exits the example_basic app. The remaining 3 keys don't affect the basic example.

**Comment by abcminiuser** [comment] 2019-09-08 05:43
I've fixed the offset key indexes - looking around, it seems the StreamDeck XL returns a few bytes of header data before the key payload.

I've added key image support to the latest commit in the `streamdeckxl` branch, could you please try it? I'm not hopeful it'll just work first time, but without hardware here to test with I'm stuck coding against the reverse engineered protocol published online.

**Comment by pointshader** [comment] 2019-09-09 05:04
@abcminiuser Your code mostly worked, just needed to fix the slicing logic (I think it was javascript style instead of python style) and update the key rotation. All 3 examples confirmed working on my XL, thank you so much for the pass at the key image support!

I've opened PR #16 with my changes.

**Comment by abcminiuser** [comment] 2019-09-09 07:42
Awesome! I'll merge it tonight and make a new release. Thanks for the help.

**Comment by abcminiuser** [comment] 2019-09-09 08:52
Fixed in 9c9614ab831b5f54539b7515532511c8c8caaf49, and pushed to PyPi as version 0.4.0. Thanks @pointshader !

**Closed by abcminiuser** 2019-09-09 08:52 UTC
Labels: help wanted
