### ISSUE TITLE
ProbeError when running under Manjaro

### ISSUE THREAD

**Issue by lamaral** [abcminiuser/python-elgato-streamdeck#26] opened 2019-10-20 23:24 UTC
Hi, 

I'm trying to use the streamdeck library under Manjaro 18.1.1 but I'm getting an error related with the HID backends. 

```
Traceback (most recent call last):
  File "streamdeck.py", line 377, in <module>
    streamdecks = DeviceManager().enumerate()
  File "/usr/lib/python3.7/site-packages/StreamDeck/DeviceManager.py", line 83, in __init__
    self.transport = self._get_transport(transport)
  File "/usr/lib/python3.7/site-packages/StreamDeck/DeviceManager.py", line 75, in _get_transport
    raise ProbeError("Probe failed to find any functional HID backend.", probe_errors)
StreamDeck.DeviceManager.ProbeError: ('Probe failed to find any functional HID backend.', {'hid': TypeError("enumerate() got an unexpected keyword argument 'vid'"), 'hidapi': TypeError("enumerate() got an unexpected keyword argument 'vid'")})
```

The same script was working previously under Debian Buster.

I'm not sure about what additional info to provide to you here, so feel free to request any additional info that you need.

**Comment by lamaral** [comment] 2019-10-20 23:37
I noticed some changes on your last commit regarding hid/hidapi. 
I tried uninstalling hidapi and installing hid via pip and now I get the following:

```
Found 1 Stream Deck(s).

Traceback (most recent call last):
  File "streamdeck.py", line 385, in <module>
    main(deck)
  File "streamdeck.py", line 65, in main
    deck.open()
  File "/usr/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeck.py", line 116, in open
    self._reset_key_stream()
  File "/usr/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeckOriginal.py", line 79, in _reset_key_stream
    self.device.write(payload)
  File "/usr/lib/python3.7/site-packages/StreamDeck/Transport/HID.py", line 134, in write
    return self.hid.write(payload)
  File "/usr/lib/python3.7/site-packages/hid/__init__.py", line 149, in write
    return self.__hidcall(hidapi.hid_write, self.__dev, data, len(data))
  File "/usr/lib/python3.7/site-packages/hid/__init__.py", line 140, in __hidcall
    raise HIDException(err)
hid.HIDException: None
```

**Comment by lamaral** [comment] 2019-10-21 21:48
Hi Dean,

I'll test the code from git tomorrow night. Thanks for looking into the issue.

**Comment by lamaral** [comment] 2019-10-25 21:20
Sorry for taking so long to provide feedback. 
I had the chance to test 0.6.1 today and it works if I only have `hidapi` installed. 

If I install `hid` instead of `hidapi` or both at the same time, the `DeviceManager().enumerate()` function will return an empty list.

**Comment by abcminiuser** [comment] 2019-10-26 00:03
Hrm. I think I've found *one* of the causes of the issues -- the `hid` library transport supports multiple backends on Linux, and the one it tries first (hidraw) doesn't work with StreamDecks properly. Annoyingly the HID library doesn't have a way to force one or the other, so I guess I'll just have to fork the darn thing.

For now, you should be able to get this working by uninstalling the `libhidapi-hidraw0` package on your system, but that could potentially break other HID applications.

**Comment by abcminiuser** [comment] 2019-11-13 09:15
@lamaral can you confirm this is now fixed?

**Comment by lamaral** [comment] 2019-11-13 17:12
Yes, it is working properly with `hid` uninstalled.

**Closed** 2019-11-13 19:34 UTC
Labels: bug
