### ISSUE TITLE
Can't Open Streamdeck

### ISSUE THREAD

**Issue by coolman4** [abcminiuser/python-elgato-streamdeck#61] opened 2021-01-04 02:36 UTC
**Describe the bug**
Please give a clear and concise description of what the bug is.
Streamdeck give error that won't allow me to open it on linux chromebook
**To Reproduce**
Please list the steps to reproduce the behavior.
use stream deck in command prompt on Linux Chromebook
**StreamDeck Information**
List the model of StreamDeck(s) you are using here.
Streamdeck original
**System Information**
List details about your operating system and hardware setup here, including OS name and version, and the version of any library dependencies you are using.
Chrome OS, Version 87.0.4280.109 (Official Build) (64-bit)
You should also include the version(s) of the library you are using - if not using a tagged release, list the commit hash you are testing here.
I don't know

**Comment by coolman4** [comment] 2021-01-04 03:04
Also, Error output is
`brysonguwin09@penguin:~$ streamdeck
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)`

**Comment by Gambloide** [comment] 2021-01-21 21:53
It sounds like you are looking for [streamdeck-ui](https://github.com/timothycrosley/streamdeck-ui/), which has the `streamdeck` command you seem to try to run.

If you still have this problem, it would probably be good to add your report to https://github.com/timothycrosley/streamdeck-ui/issues/51. Others have reported the same error there.

`streamdeck-ui` is built on `python-elgato-streamdeck`.
This https://github.com/abcminiuser/python-elgato-streamdeck/issues/30#issuecomment-562902281 explains the difference between the two projects.

_Possible duplicate of #30_

**Comment by abcminiuser** [comment] 2021-01-30 10:01
Yes, this looks like it's actually for the `streamdeck-ui` project that builds on top of this - thanks for the help @Gambloide . I'll close this for now, please re-open if you have issues with this library.

**Closed by abcminiuser** 2021-01-30 10:01 UTC
Labels: bug
