### ISSUE TITLE
Stream Deck mini updates the keys twice

### ISSUE THREAD

**Issue by kcsajtai** [abcminiuser/python-elgato-streamdeck#13] opened 2019-05-28 12:23 UTC
The streamdeck mini repeats the last image before updating to a new one. So if I update key0 and sometime later for example key5 then key5 first shows the image that has been sent to key0 for 0.1 or 0.2 sec then shows the image that is actually sent to it. The included basic example also has this issue.

**Comment by abcminiuser** [comment] 2019-06-04 12:06
Unfortunately I don't have a StreamDeck mini to test on, only the original. @Aetherdyne do you see this behavior on your device?

**Comment by Aetherdyne** [comment] 2019-06-04 19:59
It sounds like the same thing that I mentioned in the last comment on my pull request [here](https://github.com/abcminiuser/python-elgato-streamdeck/pull/9#issuecomment-464714311).  It's happened as long as I've had the mini showing any images at all.

[Here's a shakycam video](https://youtu.be/asN727gJr8Y) of the current example-basic script.  Note that, as I press Key 0, the exit icon briefly appears on that button.  And when I press the Exit key at the end, it briefly flashes the face icon that the others normally show.  On the keys I press in between these, the glitch isn't very noticeable, presumably because it's just repeating one of the images that those buttons normally show.

I've never noticed it before, but right before the button images appear, you can also see Key 0 showing a fragment of the startup logo.

**Comment by kcsajtai** [comment] 2019-06-04 20:17
Yepp same issue. It's a bit harder to spot on the basic example since it's using mostly the same images. But if you have like 6 different images each with different states then it becomes quite noticable. Thanks for looking into it :) This glitch aside I really like this  project :)

**Comment by tappster** [comment] 2019-06-25 18:07
I am having a problem with deck.set_key_image(key,image) call back to set the image on the streamdeck.
It is only with the Raspberry Pi. That call slows my program down. Button image  update is slowed down intermittently. Don't see the flashing as in the basic example but the delay is there. Any ideas?
I used a Windows computer to design and did not see the problem. Also if I make the image 0 on the windows computer it keeps the image that Streamdeck program put in. Neat if Raspberry would do that.

**Comment by abcminiuser** [comment] 2019-07-06 01:42
@tappster USB HID on the RPi is much slower for me - although I don't know if the cause is something in the Python USBHID wrapper library, or the underlying HID library. When I used this on my Pi for my home automation client I just kept the button images in a local cache and only updated it on the device when I knew it had to change (i.e. filter out repeated calls with an identical image) which made it run at an acceptable speed.

**Comment by jbman35** [comment] 2019-08-08 08:17
Hello,
Same problem here by connecting StreamDeck mini on Linux Desktop computer. Each time I call deck.set_key_image(key,image) the new image appear on another button and "slides" to its new position. Does anyone have any idea on how to fix this behavior?

When I run the basic examples, the image update between key press and key release is seamless.

Thanks,

**Comment by abcminiuser** [comment] 2019-09-11 11:54
Can someone with a StreamDeck Mini please test the `feature_new_encoding` branch? If it still works for the Mini I'll be able to simplify a bunch of code.

**Comment by michaelkleinhenz** [comment] 2019-09-11 12:18
I just found out that my similar issue #17 is only appearing when using an USB hub. Maybe this is also the issue here?

**Comment by michaelkleinhenz** [comment] 2019-09-11 12:24
Ok, more exploring. It's aparrently *not* the USB hub. The device works before I run the animation example. After running it, it starts behaving weird, does not respond to keys, matches the wrong keys etc. See #17

**Comment by abcminiuser** [comment] 2019-09-11 12:41
Sounds like I'm missing a termination flag in the header that resets the buffer in the receive side.

Since it looks like the mini and original share the same frame format, could you try the branch I mention above and see if it works as well as the current code? If it does, I can use that as a reference point and experiment with my Original and see if I can provoke a similar issue.

**Comment by abcminiuser** [comment] 2019-09-14 00:45
After I figured out the StreamDeck Original and StreamDeck Mini share the same wire protocol with only orientation and key ordering differences, I did some refactoring. I've now found that I can also trigger the reported partial key image update bug on my original.

I believe I've fixed in in the `feature_new_encoding` branch for both devices. @michaelkleinhenz feel like testing it out?

**Comment by Aetherdyne** [comment] 2019-09-16 00:52
I tested the new branch on my mini, and the basic example appeared to be working just like it always has, even after running the animation example.

That is, the basic example still briefly flashes up an image of whatever button was last drawn or pressed whenever you press a new button, but I didn't notice anything with it ignoring button presses or registering the wrong button.  

The animation example does something similar ... before drawing the new frame on the elephant buttons, it shows the CV joint animation.  Before drawing a new frame of the cube animation, it draws the elephant.  Before drawing a new frame of the CV joint, it draws the cube.  I believe it was doing that before.

**Comment by michaelkleinhenz** [comment] 2019-09-16 09:45
> I believe I've fixed in in the `feature_new_encoding` branch for both devices. @michaelkleinhenz feel like testing it out?

@abcminiuser tested the branch and it indeed resolved the issue. The basic example can be run after the animation without issues. Also, I noticed that some jittering on the animation example is also gone, the animation is now flawless. Great work!

**Comment by abcminiuser** [comment] 2019-09-16 10:52
Well that's confusing - one report that it's fixed, another that it's not. Overall I'm sure this is a definite improvement and more maintainable to boot, so I think I'll merge it.

@Aetherdyne that video looks like it's exhibiting a different issue -- I'm able to get ~30 FPS with my StreamDeck original, but it looks like your Mini is updating at less than 1 FPS, in addition to glitching. Could you please file it as a separate issue, along with details about your setup? I'm specifically after your Python version, Pillow version, and version of the HID library you are using along with the machine its running on.

**Comment by abcminiuser** [comment] 2019-09-16 11:02
Fixed merged in https://github.com/abcminiuser/python-elgato-streamdeck/commit/ae941201a4375aefe7f0f462479a827b83106ef9 and released as version 0.5.0. Please reopen new issues against the latest version, so I can properly track what's still outstanding. Thanks everyone!

**Closed by abcminiuser** 2019-09-16 11:02 UTC
Labels: help wanted
